name: Another Job
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: src

jobs:
  checkout_repo:
    name: Setup Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      - run: node index.js

    